n_hier: 3
hier_strides: ["d1", "d1", "d1"]
hier_num_layers: [6, 6, 6]
hier_hidden_size: [384, 384, 384]
hier_ffn_hidden_size: [1536, 1536, 1536]
hier_num_attention_heads: [6, 6, 6]

hier_tensor_model_parallel_size: [3, 6, 3]
hier_pipeline_model_parallel_size: [1, 1, 1]

# kv_channels: 64
