n_hier: 1
hier_strides: ["d1"]
hier_num_layers: [12]
hier_hidden_size: [384]
hier_ffn_hidden_size: [1536]
hier_num_attention_heads: [6]

hier_tensor_model_parallel_size: [6]
hier_pipeline_model_parallel_size: [1]

# kv_channels: 64
